version: "3.7"

services:
  app1:
    build: ./app1
    ports:
      - 8080:8080
  app2:
    build: ./app2
    ports:
      - 8081:8080
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
